Update api to 1.3 (#19)
neuroio/neuroio-python pull request #20
Opened 2021-09-08 09:51 UTC by zzkate

2021-09-08 13:20 UTC, levchik requested changes

2021-09-08 13:20 UTC, levchik commented on tests/test_stream_tokens.py
> +        "permanent=",
ну получается если без перманента то его лучше не указывать пустым

2021-09-08 13:20 UTC, levchik commented on neuroio/iam/billing/v1.py
> +    def manager_account_billing_usage(
я тут подумал что у нас же нет больше никаких менеджерских апи в этой библиотеке, и до сих пор не очень понятно нужно ли оно будет кому-либо или нет

поэтому предлагаю эти 2 менеджерских метода убрать

2021-09-08 13:21 UTC, levchik commented
Надо еще поправить coverage до 100%, потому что после твоих изменений он упал до 94,71

2021-09-10 11:31 UTC, levchik commented
Мне не очень нравится идея с вложенными классами в Client. В целом я бы сделал по другому:

- Сделать еще 2 base класса для IAM, аналогичные APIBase и APIBaseAsync (ну и в конечных классах наследовался бы от соответствующего IAM или API). Они по сути будут отличаться только Base URL запроса (api.neuroio.com, iam.neuroio.com)
- Конечные классы (типа Sources, Billing и пр) я бы назвал одинаково, например `Impl`
- Перестал разделять наши подразделы на api и iam на уровне директорий чтобы была более плоская структура для дальнейшего импорта
- Внутри getattr сделал бы ловильщика аттрибутов чтобы потом одной командой импортировать когда мы дойдем до вызова метода

Рабочий пример того, что я имею ввиду (с сеттингами надо будет немного облагородить, ну и в целом оставить параметры теми же что и сейчас):

```python
from importlib import import_module


class Catcher:

    def __init__(self, prev: str, settings: dict):
        self.prev = prev
        self.settings = settings
        self.api_version = self.settings["api_version"]

    def __getattr__(self, item):
        return Catcher(prev=f"{self.prev}.{item}", settings=self.settings)

    def __call__(self, *args, **kwargs):
        method = self.prev.split(".")[-1]
        path = ".".join(self.prev.split(".")[:-1])
        v1_module = import_module(f"app.{path}.v{self.api_version}")
        cls = getattr(v1_module, "Impl")
        inst = cls(settings=self.api_settings)
        return getattr(inst, method)(*args, **kwargs)


class Client:

    def __init__(self, api_version: int = 1, token: str = ""):
        self.api_version = api_version
        self.token = token
        self.api_settings = {"token": token, "api_version": api_version}

    def __getattr__(self, item):
        return Catcher(prev=item, settings=self.api_settings)
```

2021-09-10 11:32 UTC, levchik commented on docs/spaces.md
> +response = c.spaces.lists.spaces.all()
Я имел ввиду что lists станет отдельным модулем чтобы вызывалось вот так `c.lists.spaces.all()`

2021-09-10 11:37 UTC, levchik commented on neuroio/api/sources/v1.py
> +        license: int,
так, я посмотрел внимательней и license везде у нас str а не int

2021-09-10 11:39 UTC, levchik commented on neuroio/iam/licenses/sources/v1.py
> +    def get(self, id: int) -> Response:
id у лицензий везде str, а не int

2021-09-10 21:35 UTC, zzkate commented
> ```python
> return Catcher(prev=item, settings=self.api_settings)
> ```

Попробовала - получила перполнение стека - ограничения и правда нигде нету.. RecursionError: maximum recursion depth exceeded in comparison

2021-09-14 10:16 UTC, levchik approved these changes

2021-09-14 10:18 UTC, merged