Fixed a bug of creating and searching with image as binary data
neuroio/neuroio-python pull request #21
Opened 2021-09-09 08:55 UTC by a-l-meyer

Besides <class '_io.BufferedReader'> and tuple(str, '_io.BufferedReader') accepted binary data 

Create:
`client.persons.create(image=f.read(), ... )`

Search:
`client.persons.search(f.read())`

2021-09-09 14:16 UTC, smilemakc commented on neuroio/api/persons/v1.py
>          files = {"image": ("image", image, "image/jpeg")}
Думаю было бы лучше соблюсти консистентность построения схожих параметров. Выше и далее по коду используется новый метод prepare_image_processing(image) для этого

2021-09-09 14:16 UTC, smilemakc commented on neuroio/utils.py
> +        ("image.jpg", io.BytesIO(image)) if isinstance(image, bytes) else image
На мой взгляд, здесь не мешало бы проверить что image соответствует ожидаемым типам, а если нет - бросить исключение

2021-09-09 14:16 UTC, smilemakc commented on neuroio/api/persons/v1.py
>          files = {"image": ("image", image, "image/jpeg")}
тяже история с построением схожих параметров

2021-09-10 12:47 UTC, levchik requested changes
Хочется увидеть вновь 100% покрытия

2021-09-13 11:16 UTC, levchik commented on neuroio/utils.py
> +    return {"image": ("image.jpg", image_data, "image/jpeg")}
а почему мы всегда считаем что это jpeg? по идее нужно либо брать то же расширение если это файл или не ставить расширение если это байты. про content-type - если можно не ставить его то лучше не ставить

2021-09-14 08:56 UTC, merged